flaskpage/routes.py
from datetime import datetime
from sqlalchemy import or_
from flask import render_template, url_for, flash, abort, redirect, request, Blueprint, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from flaskpage import db, bcrypt
from flaskpage.models import User, Elements, Pages
from flaskpage.utils import send_reset_email
from flaskpage.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm

usersBP = Blueprint('users', __name__)
mainBP = Blueprint('main', __name__)
errorsBP = Blueprint('errors', __name__)

@mainBP.route("/page/<int:page_id>", methods=['GET'])
@login_required
def page(page_id):
	creator = (current_user.id == Pages.query.get(page_id).author.id)
	print(current_user.id)
	print(Pages.query.get(page_id).author.id)
	print(creator)
	return render_template('page.html', page_id=page_id, creator=creator)

@mainBP.route("/page/<int:page_id>", methods=['POST'])
@login_required
def page_io(page_id):
	data = request.get_json(force=True)
	if data[0] == 'refresh':
		query = Elements.query.filter_by(page_id=page_id).all()
		elements = []
		for i in range(len(data[1])):
			if not Elements.query.get(i) and data[1][i] != 946677600000:
				data_string = "{\"type\": -1, \"x\": 0, \"y\": 0, \"img_date\": -1}"
				element = Elements(id=i, page_id=page_id, data=data_string, content=None, last_mod=datetime(2000, 1, 1))
				elements.append(element)
		for element in query:
			new_element = element.id >= len(data[1])
			if new_element or element.last_mod.timestamp()*1000 > data[1][element.id]:
				if not new_element and int(element.data.split(" ")[1].split(",")[0]) == 1 and int(element.data.split(" ")[7].split("}")[0]) < data[1][element.id]:
					element.content = ""
				if not new_element and int(element.data.split(" ")[7].split("}")[0]) < data[1][element.id]:
					element.content = ""
				elements.append(element)
		return jsonify(obj=[element.serialize() for element in elements])
	if data[0] == 'text':
		search_id = data[1]
		return str(User.query.filter(User.id > search_id).all())
	elif data[0] == "send":
		if current_user != Pages.query.get(page_id).author and Pages.query.get(page_id).access_mode == 1:
			abort(403)
		element = Elements.query.get(data[6])
		if element:
			db.session.delete(element)
		if data[1] != -1:
			data_string = "{\"type\": "+str(data[1])+", \"x\": "+str(data[2])+", \"y\": "+str(data[3])+", \"img_date\": "+str(data[5])+"}"
			element = Elements(id=data[6], page_id=page_id, data=data_string, content=data[4], last_mod=datetime.fromtimestamp(data[5]/1000))
			if element.last_mod > datetime.now():
				element.last_mod = datetime.now()
			db.session.add(element)
		page = Pages.query.get(page_id)
		page.last_ver = datetime.now()
		db.session.commit()
		return "OK"
	elif data[0] == "load":
		if current_user != Pages.query.get(page_id).author and Pages.query.get(page_id).access_mode == 1:
			abort(403)
		return jsonify(obj=[element.serialize() for element in Elements.query.filter_by(page_id=page_id).all()])
	elif data[0] == "getTitle":
		return jsonify(Pages.query.get(page_id).name)
	elif data[0] == "setTitle":
		page = Pages.query.get(page_id)
		if current_user != page.author:
			abort(403)
		page.name = data[1]
		page.last_ver = datetime.now()
		db.session.commit()
		return "OK set"
	elif data[0] == "getPubl":
		return jsonify(Pages.query.get(page_id).access_mode)
	elif data[0] == "setPubl":
		page = Pages.query.get(page_id)
		if current_user != page.author:
			abort(403)
		page.access_mode = data[1]
		page.last_ver = datetime.now()
		db.session.commit()
		return "OK set"
	elif data[0] == "update":
		if current_user != Pages.query.get(page_id).author and Pages.query.get(page_id).access_mode == 1:
			abort(403)
		element = Elements.query.get(data[4])
		if element:
			img_data = element.data.split(" ")[7].split("}")[0]
			element.data = "{\"type\": "+str(data[1])+", \"x\": "+str(data[2])+", \"y\": "+str(data[3])+", \"img_date\": "+img_data+"}"
			element.last_mod = datetime.fromtimestamp(data[5]/1000)
			page = Pages.query.get(page_id)
			page.last_ver = datetime.now()
			db.session.commit()
			return "OK edit"
		else:
			data_string = "{\"type\": "+str(data[1])+", \"x\": "+str(data[2])+", \"y\": "+str(data[3])+", \"img_date\": "+str(data[5])+"}"
			element = Elements(id=data[4], page_id=page_id, data=data_string, last_mod=datetime.fromtimestamp(data[5]/1000))
			if element.last_mod > datetime.now():
				element.last_mod = datetime.now()
			db.session.add(element)
			page = Pages.query.get(page_id)
			page.last_ver = datetime.now()
			db.session.commit()
			return "OK new"
	return "Invalid Request"

@mainBP.route("/pages", methods=['GET'])
@login_required
def pages():
	return render_template('pages.html')

@mainBP.route("/pages", methods=['POST'])
@login_required
def pages_io():
	data = request.get_json(force=True)
	if data[0] == "load":
		return jsonify(obj=[page.serialize() for page in Pages.query.filter(or_(Pages.access_mode==0, Pages.user_id==current_user.id)).all()])
	if data[0] == "new":
		page = Pages(user_id=current_user.id, name="New", access_mode=0, last_ver=datetime.now())
		db.session.add(page)
		db.session.commit()
		return page.serialize()

@usersBP.route("/account/<int:user_id>", methods=['GET', 'POST'])
@login_required
def account(user_id):
	if current_user.id != user_id:
		return redirect(url_for('main.pages'))
	else:
		user = User.query.filter_by(id=user_id).first_or_404()
		form = UpdateAccountForm()
		form.user_id = user_id
		if form.validate_on_submit():
			user.username = form.username.data
			user.email = form.email.data
			db.session.commit()
			flash('Account has been updated!', 'success')
			return redirect(url_for('users.account', user_id=user.id))
		elif request.method == 'GET':
			form.username.data = user.username
			form.email.data = user.email
		page = request.args.get('page', 1, type=int)
		return render_template('account.html', title='Account', user=user, form=form)

@usersBP.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.pages'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Account has been created successfully!', 'success')
		return redirect(url_for('users.register'))
	return render_template('register.html', title='Register', form=form)

@mainBP.route("/")
@usersBP.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.pages'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			user.last_seen = datetime.utcnow()
			db.session.commit()
			return redirect(next_page) if next_page else redirect(url_for('main.pages'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')
	return render_template('login.html', title='Login', form=form)

@usersBP.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('users.login'))

@usersBP.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.homework'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)

@usersBP.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.homework'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Your password has been updated! You are now able to log in', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

@errorsBP.app_errorhandler(404)
def error_404(error):
	return render_template('errors/404.html'), 404

@errorsBP.app_errorhandler(403)
def error_403(error):
	return render_template('errors/403.html'), 403

@errorsBP.app_errorhandler(500)
def error_500(error):
	return render_template('errors/500.html'), 500

flaskpage/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="content-section mb-0">
	<form method="POST" action="" enctype="multipart/form-data">
		{{ form.hidden_tag() }}
		<fieldset class="form-group mb-2">
			<legend class="border-bottom mb-4">Account Info</legend>
			<div class="row">
				<div class="form-group col-sm-6 col-lg-5 col-xl-4">
					{{ form.username.label(class="form-control-label mb-1") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid p-1") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg p-1", type="username") }}
					{% endif %}
				</div>
				<div class="form-group col-sm-6 col-lg-5 col-xl-4">
					{{ form.email.label(class="form-control-label mb-1") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid p-1") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg p-1", type="email") }}
					{% endif %}
				</div>
			</div>
		</fieldset>
		<div class="form-group">
			<a class="btn btn-secondary" href="{{ url_for('main.pages') }}">Back</a>
			{{ form.submit(class="btn btn-primary") }}
		</div>
  </form>
</div>
{% endblock content %}

flaskpage/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libraries/bootstrap.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libraries/main.css') }}">
	<script src="{{ url_for('static', filename='libraries/p5.js') }}"></script>
	<script src="{{ url_for('static', filename='libraries/jquery.js') }}"></script>
	<script src="{{ url_for('static', filename='libraries/bootstrap.js') }}"></script>

	{% if title %}
		<title>{{ title }} page</title>
	{% else %}
		<title>Virtual Board</title>
	{% endif %}
</head>
<body>
	<main class="container">
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category, message in messages %}
				<div class="alert alert-{{ category }}">
					{{ message }}
				</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
		{% block content %}{% endblock %}
	</main>
</body>
</html>

flaskpage/templates/login.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form class="container" method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group mb-0 row">
				<legend class="border-bottom mb-4">Log In</legend>
				<div class="row">
					<div class="form-group col-sm-11 col-lg-11 col-xl-10">
						{{ form.email.label(class="form-control-label mb-1") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.email(class="form-control form-control-lg p-1", type="email") }}
						{% endif %}
					</div>
					<div class="col-xl-12"></div>
					<div class="form-group col-sm-11 col-lg-11 col-xl-10 mb-2">
						{{ form.password.label(class="form-control-label mb-1") }}
						{% if form.password.errors %}
							{{ form.password(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.password.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.password(class="form-control form-control-lg p-1", type="password") }}
						{% endif %}
					</div>
				</div>
			</fieldset>
			<div class="form-group mt-1 ml-2 row">
				{{ form.remember(class="form-check-input mr-2 mt-1", style="margin-top: 0px; position: static;") }}
				{{ form.remember.label(class="form-check-label") }}
			</div>
			<div class="form-group border-top pt-3 mb-0 row">
				{{ form.submit(class="btn btn-primary") }}
				<small class="text-dark ml-2 pt-2">
					<a href="{{ url_for('users.register') }}">Register?</a>
				</small>
			</div>
			<div class="form-group row">
				<small class="text-dark ml-0 pt-1">
					<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
				</small>
			</div>
		</form>
	</div>
{% endblock content %}

flaskpage/templates/page.html
<!DOCTYPE html>
<html>
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libraries/bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libraries/main.css') }}">
		<script src="{{ url_for('static', filename='libraries/p5.js') }}"></script>
		<script src="{{ url_for('static', filename='libraries/cycle.js') }}"></script>
		<script src="{{ url_for('static', filename='libraries/jquery.js') }}"></script>
		<script src="{{ url_for('static', filename='libraries/bootstrap.js') }}"></script>

		<title>Virtual Board</title>
</head>
<body class="mt-0 position-fixed overflow-hidden" onresize="resizeWin()">
	<button></button>
	<script>isCreator = "{{ creator | safe }}"</script>
	<script>pageID = "{{ page_id | safe }}"</script>
	<script>pagesURL = "{{ url_for('main.pages') | safe }}"</script>
	<script>accountURL = "{{ url_for('users.account', user_id=current_user.id) | safe }}"</script>
	<script>logoutURL = "{{ url_for('users.logout') | safe }}"</script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/setup.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/draw.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/server.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/main.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/input.js') }}"></script>
</body>
</html>

flaskpage/templates/pages.html
<!DOCTYPE html>
<html>
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libraries/bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libraries/main.css') }}">
		<script src="{{ url_for('static', filename='libraries/p5.js') }}"></script>
		<script src="{{ url_for('static', filename='libraries/cycle.js') }}"></script>
		<script src="{{ url_for('static', filename='libraries/jquery.js') }}"></script>
		<script src="{{ url_for('static', filename='libraries/bootstrap.js') }}"></script>

		<title>Virtual Board</title>
</head>
<body class="mt-0 position-fixed overflow-hidden" onresize="resizeWin()">
	<button></button>
	<script>pageID = "{{ page_id | safe }}"</script>
	<script>pagesURL = "{{ url_for('main.pages') | safe }}"</script>
	<script>accountURL = "{{ url_for('users.account', user_id=current_user.id) | safe }}"</script>
	<script>logoutURL = "{{ url_for('users.logout') | safe }}"</script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/setup.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='java_script/pages.js') }}"></script>
</body>
</html>

flaskpage/templates/register.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form class="container" method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group mb-0 row">
				<legend class="border-bottom mb-4">Add User</legend>
				<div class="row">
					<div class="form-group col-sm-6 col-lg-5 col-xl-4">
						{{ form.username.label(class="form-control-label mb-1") }}
						{% if form.username.errors %}
							{{ form.username(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.username.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.username(class="form-control form-control-lg p-1", type="username") }}
						{% endif %}
					</div>
					<div class="form-group col-sm-6 col-lg-5 col-xl-4">
						{{ form.email.label(class="form-control-label mb-1") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.email(class="form-control form-control-lg p-1", type="email") }}
						{% endif %}
					</div>
					<div class="col-xl-4"></div>
					<div class="form-group col-sm-6 col-lg-5 col-xl-4">
						{{ form.password.label(class="form-control-label mb-1") }}
						{% if form.password.errors %}
							{{ form.password(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.password.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.password(class="form-control form-control-lg p-1", type="password") }}
						{% endif %}
					</div>
					<div class="form-group col-sm-6 col-lg-5 col-xl-4">
						{{ form.confirm_password.label(class="form-control-label mb-1") }}
						{% if form.confirm_password.errors %}
							{{ form.confirm_password(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.confirm_password.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.confirm_password(class="form-control form-control-lg p-1", type="password") }}
						{% endif %}
					</div>
				</div>
			</fieldset>
			<div class="form-group border-top pt-3 row">
				{{ form.submit(class="btn btn-primary") }}
				<small class="text-dark ml-2 pt-2">
				  <a href="{{ url_for('users.login') }}">Login?</a>
				</small>
			</div>
		</form>
	</div>
{% endblock content %}

flaskpage/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form class="" method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group mb-0">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="row container">
					<div class="form-group col-sm-9 col-lg-8 col-xl-7 row">
						{{ form.email.label(class="form-control-label mb-1") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid p-1") }}
							<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.email(class="form-control form-control-lg p-1", type="email") }}
						{% endif %}
					</div>
				</div>
			</fieldset>
			<div class="form-group border-top pt-3">
				{{ form.submit(class="btn btn-primary") }}
				<small class="text-dark ml-2 pt-2">
				  <a href="{{ url_for('users.login') }}">Login?</a>
				</small>
			</div>
		</form>
	</div>
{% endblock content %}

flaskpage/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-primary") }}
			</div>
		</form>
	</div>
{% endblock content %}